### ISSUE TITLE
Doesn't work with inferno

### ISSUE THREAD

**Issue by halcaponey** [sadick254/scoped-css#1]
Hi 
That code : 
```
import { render } from 'inferno';
import scoped from 'scoped-style';
import { createElement } from 'inferno-create-element';

const styled = scoped(createElement);

const Button = styled('button')`
  background: ${props => props.primary ? "orange" : "gray"};
  border: none;
  border-radius: 2px;
  :hover {
    padding: 10px;
  }
`
const App = () => (
    <div>
        <Button primary>Click me !</Button>
    </div>
)

render(<App />, document.body);
```
doesn't work, so I went into investigation mode and it seems that changing from this : 
```
if ("class" in props) {
      attr.className = `${className} ${props.class}`;
}
```
to this : 
```
attr.className = className
if ("class" in props) {
     attr.className += ` ${props.class}`;
}
```
fixes the probleme.

I would submit a pull request but : 
1. I've never done any pull request before so I don't exactly know how that works
2. I haven't tested my change in React, Preact, or Hyperapp and I don't want to break things

**Comment by sadick254** [comment]
I should have probably added tests to this library first before releasing it. Am going to add tests to make it easier for contributions.
Here is an article that i think will point you to the right directions on [pull request](https://yangsu.github.io/pull-request-tutorial/)
